place_list = ["Tokyo","Kyoto","Canada","Australia","Spain"]
print("Here is the original list: ",place_list)
print("Here is the list after sorted(): ",sorted(place_list))
print("Here is the list still in original: ",place_list)
print("Reverse alphabetical list: ",sorted(place_list,reverse=True))
print("Here is the list still in original: ",place_list)
place_list.reverse()
print("Here is the list after reverse(): ",place_list)
place_list.reverse()
print("Here is the list still in original: ",place_list)
place_list.sort()
print("Here is the list after sort(): ",place_list)
place_list.sort(reverse=True)
print("Here is the list after sort(reverse=True): ",place_list)